apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: oebs-melosys-api
  namespace: team-oebs
  labels:
    team: team-oebs
spec:
  image: repo.adeo.no:5443/oebs/oebs-melosys-api-prod:1.2.19
  port: 8080
  replicas:
    min: 3
    max: 4
    cpuThresholdPercentage: 50
  liveness:
    path: /internal/isalive
    initialDelay: 60
    timeout: 10
  readiness:
    path: /internal/isready
    initialDelay: 60
    timeout: 10
  resources:
    requests:
      cpu: 400m
      memory: 1024Mi
    limits:
      cpu: 4000m
      memory: 2048Mi
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
         - application: oebs-melosys-api
           namespace: team-oebs
           cluster: prod-fss
  kafka:
    pool: nav-prod

  prometheus:
    enabled: true
    path: /actuator/prometheus
  vault:
    enabled: true
    paths:
      - kvPath: "kv/prod/fss/oebs-melosys-api/team-oebs/apps-user"
        mountPath: "/secrets/oebs-p/apps-user"
      - kvPath: "kv/prod/fss/oebs-melosys-api/team-oebs/app-name"
        mountPath: "/secrets/oebs-p/app-name"
      - kvPath: "kv/prod/fss/oebs-melosys-api/team-oebs/jdbc-url"
        mountPath: "/secrets/oebs-p/jdbc-url"
  ingresses:
     - "https://oebs-melosys-api.intern.nav.no"
