apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: oebs-melosys-api-t1
  namespace: team-oebs
  labels:
    team: team-oebs
spec:
  image: repo.adeo.no:5443/oebs/oebs-melosys-api-t1:1.2.20
  port: 8080
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  liveness:
    path: /internal/isalive
    initialDelay: 60
    timeout: 10
  readiness:
    path: /internal/isready
    initialDelay: 60
    timeout: 10
  resources:
    requests:
      cpu: 400m
      memory: 1024Mi
    limits:
      cpu: 4000m
      memory: 2048Mi
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
         - application: oebs-melosys-api-t1
           namespace: team-oebs
           cluster: dev-fss
  prometheus:
    enabled: true
    path: /actuator/prometheus
  vault:
    enabled: true
    paths:
      - kvPath: "kv/preprod/fss/oebs-melosys-api-t1/team-oebs/apps-user"
        mountPath: "/secrets/oebst1/apps-user"
      - kvPath: "kv/preprod/fss/oebs-melosys-api-t1/team-oebs/app-name"
        mountPath: "/secrets/oebst1/app-name"
      - kvPath: "kv/preprod/fss/oebs-melosys-api-t1/team-oebs/jdbc-url"
        mountPath: "/secrets/oebst1/jdbc-url"
  ingresses:
     - "https://oebs-melosys-api-t1.dev.intern.nav.no"