apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: oebs-melosys-api
  namespace: team-oebs
  labels:
    team: team-oebs
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 3
    max: 4
    cpuThresholdPercentage: 50
  liveness:
    path: /internal/isalive
    initialDelay: 60
    timeout: 10
  readiness:
    path: /internal/isready
    initialDelay: 60
    timeout: 10
  resources:
    requests:
      cpu: 70m
      memory: 600Mi
    limits:
      memory: 800Mi
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
         - application: oebs-melosys-api
           namespace: team-oebs
           cluster: prod-fss
  kafka:
    pool: nav-prod

  prometheus:
    enabled: true
    path: /actuator/prometheus
  vault:
    enabled: true
    paths:
      - kvPath: "kv/prod/fss/oebs-melosys-api/team-oebs"
        mountPath: "/var/run/secrets/nais.io/vault"

  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
  ingresses:
     - "https://oebs-melosys-api.intern.nav.no"
