
no.nav.security.jwt:
  issuer:
    azure:
      # < oeb-melosys-api clientinfo >
      # discoveryurl: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/v2.0/.well-known/openid-configuration
      # accepted_audience: 44484cc8-2444-4215-beed-4cc7505e3ab7
      # proxyurl: http://webproxy-nais.nav.no:8088
      # cookie_name: azure_token
      # reststs:
      #  discoveryurl: https://security-token-service.dev.adeo.no/rest/v1/sts/.well-known/openid-configuration
      #  accepted_audience: srv_oebs
      # proxyurl: http://webproxy-utvikler.nav.no:8088


# logging.level.org.springframework: INFO
# logging.level.no.nav: DEBUG

server:
  port: 8080

spring:
  profiles:
     active: nais # local
  application:
    name: oebs-melosys-api-q1

  kafka:
    retry-max-attempts: 10
    retry-backoff-period: 30000
    authorization-exception-retry-interval-secs: 60
    bootstrap-servers: ${KAFKA_BROKERS}
    properties:
      security.protocol: SSL
      ssl:
        keystore:
          type: PKC12
          location: ${KAFKA_KEYSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        truststore:
          type: PKC12
          location: ${KAFKA_TRUSTSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        endpoint.identification.algorithm:
    consumer:
      group-id: "Oebs-Melosys-api-q1"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      topic: faktura-bestilt.v1-q2
      enable-auto-commit: false
      max-poll-records: 1

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
  flyway:
    locations: classpath:/db/migration,classpath:/db/oracle
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
    show-sql: false
    open-in-view: false
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics

# Quartz
using:
  spring:
    schedulerFactory: true

springdoc:
  packagesToScan: no.nav.oebs.melosys
  override-with-generic-response: false
  remove-broken-reference-definitions: false
  swagger-ui:
    disable-swagger-default-url: true
    tags-sorter: alpha