server:
  port: 8080

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${OEBS_USERNAME}
    password: ${OEBS_PASSWORD}
    url: ${OEBS_URL}
  flyway:
    locations: classpath:/db/migration,classpath:/db/oracle
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    show-sql: false
    open-in-view: false
  jackson:
    parser:
      allow-numeric-leading-zeros: true
  quartz:
    job-store-type: jdbc
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    properties:
      security.protocol: SSL
      ssl:
        keystore:
          type: PKCS12
          location: ${KAFKA_KEYSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        truststore:
          type: ${KAFKA_SSL_TRUSTSTORE}
          location: ${KAFKA_TRUSTSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        endpoint.identification.algorithm:
    consumer:
      group-id: ${NAIS_APP_NAME}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      max-poll-records: 1

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 5
      client-id: ${KAFKA_PRODUCER_CLIENT_ID}

# Quartz
using:
  spring:
    schedulerFactory: true

app:
  kafka:
    retry-max-attempts: '5'
    retry-backoff-period-ms: '30000'
    retry-interval-max-length: '600000'
    topics:
      faktura-status: ${KAFKA_TOPIC_FAKTURA_STATUS}
      test-faktura: ${KAFKA_TOPIC_TEST_FAKTURA}

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    org:
      springframework: info
